package profile

func defaultProfiles() []Profile {
	return []Profile{
		{
			ID:          "douyin.desktop.macos",
			Surface:     SurfaceDesktop,
			Family:      "douyin.media_feed",
			SupportTier: "tier_a",
			ViewModel:   "canvas_heavy",
			Match: Match{
				AppNames:  []string{"抖音", "douyin"},
				BundleIDs: []string{"com.bytedance.douyin.desktop", "com.ss.douyin"},
				DriverIDs: []string{"douyin.desktop", "douyin.desktop.macos"},
			},
			PreferredTransports: []string{
				TransportNativeCommand,
				TransportMenuInvoke,
				TransportSemanticUIAction,
				TransportVerifiedHotkey,
				TransportOCRAnchoredVisual,
				TransportVisionOrCoordinate,
			},
			Actions: []Action{
				{
					ID:                  "app.launch",
					RiskLevel:           "low",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportNativeCommand, TransportMenuInvoke, TransportSemanticUIAction},
					VerificationPolicy:  "ready_state",
					RecoveryBudget:      1,
				},
				{
					ID:                  "app.search.focus",
					RiskLevel:           "low",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportOCRAnchoredVisual},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.submit",
					RiskLevel:           "low",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportOCRAnchoredVisual},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      2,
				},
				{
					ID:                  "search.open_first",
					RiskLevel:           "low",
					RequiredReadyState:  "scene_ready",
					PreferredTransports: []string{TransportSemanticUIAction, TransportOCRAnchoredVisual, TransportVisionOrCoordinate},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      2,
				},
				{
					ID:                  "media.play",
					Aliases:             []string{"media.play_toggle"},
					RiskLevel:           "medium",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportVisionOrCoordinate},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      2,
				},
				{
					ID:                  "media.next_item",
					RiskLevel:           "low",
					RequiredReadyState:  "media_progressing",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportOCRAnchoredVisual, TransportVisionOrCoordinate},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      2,
				},
				{
					ID:                  "media.wait_until_end",
					RiskLevel:           "low",
					RequiredReadyState:  "media_progressing",
					PreferredTransports: []string{TransportSemanticUIAction, TransportOCRAnchoredVisual},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
			},
		},
		{
			ID:          "qqmusic.desktop.macos",
			Surface:     SurfaceDesktop,
			Family:      "qqmusic.player",
			SupportTier: "tier_a",
			ViewModel:   "hybrid_view",
			Match: Match{
				AppNames:  []string{"qq音乐", "qq music"},
				BundleIDs: []string{"com.tencent.qqmusic"},
				DriverIDs: []string{"qqmusic.desktop", "qqmusic.desktop.macos"},
			},
			PreferredTransports: []string{
				TransportNativeCommand,
				TransportMenuInvoke,
				TransportSemanticUIAction,
				TransportVerifiedHotkey,
				TransportStructuredText,
			},
			Actions: []Action{
				{
					ID:                  "app.search.focus",
					RiskLevel:           "low",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportStructuredText},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.submit",
					RiskLevel:           "low",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportSemanticUIAction, TransportVerifiedHotkey, TransportStructuredText},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.open_first",
					RiskLevel:           "low",
					RequiredReadyState:  "scene_ready",
					PreferredTransports: []string{TransportSemanticUIAction, TransportMenuInvoke, TransportVerifiedHotkey},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
				{
					ID:                  "media.play",
					Aliases:             []string{"media.pause", "media.play_toggle", "media.next_item"},
					RiskLevel:           "medium",
					RequiredReadyState:  "interactive",
					PreferredTransports: []string{TransportNativeCommand, TransportMenuInvoke, TransportSemanticUIAction, TransportVerifiedHotkey},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      2,
				},
			},
		},
		{
			ID:          "creative.timeline_editor.desktop.macos",
			Surface:     SurfaceDesktop,
			Family:      "creative.timeline_editor",
			SupportTier: "tier_b",
			ViewModel:   "canvas_heavy",
			Match: Match{
				AppNames: []string{"剪映", "capcut", "premiere pro", "final cut pro"},
				BundleIDs: []string{
					"com.lemon.lvoverseas",
					"com.lemon.jianying",
					"com.adobe.premierepro",
					"com.apple.finalcut",
				},
				DriverIDs: []string{
					"timeline.editor.desktop",
					"capcut.desktop",
					"jianying.desktop",
					"premiere.desktop",
					"finalcut.desktop",
				},
			},
			PreferredTransports: []string{
				TransportNativeCommand,
				TransportMenuInvoke,
				TransportSemanticUIAction,
				TransportVerifiedHotkey,
				TransportOCRAnchoredVisual,
			},
			Actions: []Action{
				{
					ID:                  "project.open_recent_first",
					RiskLevel:           "medium",
					RequiredReadyState:  "scene_ready",
					PreferredTransports: []string{TransportNativeCommand, TransportMenuInvoke, TransportSemanticUIAction, TransportVerifiedHotkey},
					VerificationPolicy:  "scene_transition",
					RecoveryBudget:      2,
				},
				{
					ID:                  "timeline.play_toggle",
					Aliases:             []string{"timeline.play"},
					RiskLevel:           "medium",
					RequiredReadyState:  "project_loaded",
					PreferredTransports: []string{TransportNativeCommand, TransportMenuInvoke, TransportVerifiedHotkey, TransportSemanticUIAction},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      2,
				},
				{
					ID:                  "export.start",
					RiskLevel:           "high",
					RequiredReadyState:  "project_loaded",
					PreferredTransports: []string{TransportNativeCommand, TransportMenuInvoke, TransportSemanticUIAction},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
			},
		},
		{
			ID:          "douyin.site",
			Surface:     SurfaceBrowser,
			Family:      "douyin.media_feed",
			SupportTier: "tier_a",
			ViewModel:   "web_media_feed",
			Match: Match{
				Domains:     []string{"douyin.com"},
				URLContains: []string{"douyin.com"},
				Titles:      []string{"抖音", "douyin"},
			},
			PreferredTransports: []string{
				TransportBrowserNavigation,
				TransportBrowserARIA,
				TransportBrowserDOM,
				TransportBrowserKeyboard,
				TransportBrowserVisual,
			},
			Actions: []Action{
				{
					ID:                  "page.navigate",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserNavigation},
					VerificationPolicy:  "dom_or_url",
					RecoveryBudget:      1,
				},
				{
					ID:                  "app.search.focus",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM, TransportBrowserKeyboard},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.submit",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM, TransportBrowserKeyboard},
					VerificationPolicy:  "dom_or_url",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.open_first",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM, TransportBrowserVisual},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
				{
					ID:                  "media.next_item",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserKeyboard, TransportBrowserDOM, TransportBrowserVisual},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
			},
		},
		{
			ID:          "qqmusic.site",
			Surface:     SurfaceBrowser,
			Family:      "qqmusic.player",
			SupportTier: "tier_a",
			ViewModel:   "web_player",
			Match: Match{
				Domains:     []string{"y.qq.com"},
				URLContains: []string{"y.qq.com"},
				Titles:      []string{"qq音乐", "qq music"},
			},
			PreferredTransports: []string{
				TransportBrowserNavigation,
				TransportBrowserARIA,
				TransportBrowserDOM,
				TransportBrowserKeyboard,
			},
			Actions: []Action{
				{
					ID:                  "page.navigate",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserNavigation},
					VerificationPolicy:  "dom_or_url",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.submit",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM, TransportBrowserKeyboard},
					VerificationPolicy:  "dom_or_url",
					RecoveryBudget:      1,
				},
				{
					ID:                  "search.open_first",
					RiskLevel:           "low",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
				{
					ID:                  "media.play_toggle",
					Aliases:             []string{"media.play", "media.pause"},
					RiskLevel:           "medium",
					RequiredReadyState:  "page_ready",
					PreferredTransports: []string{TransportBrowserARIA, TransportBrowserDOM, TransportBrowserKeyboard},
					VerificationPolicy:  "state_change",
					RecoveryBudget:      1,
				},
			},
		},
	}
}
