package config

import (
	"bytes"
	"text/template"
)

// ---------------------------------------------------------------------------
// SetupOptions — structured input from the setup wizard
// ---------------------------------------------------------------------------

// SetupOptions holds the user's choices from the interactive setup wizard.
type SetupOptions struct {
	// Provider is the model provider name: "openai", "anthropic", "google", "ollama", "custom".
	Provider string

	// ProviderAPI is the canonical provider API selected during setup.
	// When empty, BuildConfig falls back to the local provider catalog.
	ProviderAPI string

	// ProviderValues stores provider-scoped field values keyed by the setup
	// contract field ID (for example api_key, base_url, region, default_model).
	ProviderValues map[string]string

	// APIKey is the provider API key.
	// Deprecated: use ProviderValues["api_key"].
	APIKey string

	// BaseURL overrides the default base URL (required for ollama/custom).
	// Deprecated: use ProviderValues["base_url"].
	BaseURL string

	// Model is the chosen model name.
	// Deprecated: use ProviderValues["default_model"].
	Model string

	// Channel is the legacy single channel selector used by the original setup wizard.
	Channel string

	// ChannelToken is the legacy single token field used by the original setup wizard.
	ChannelToken string

	// ChannelAppToken is the legacy additional token field used by Slack setup.
	ChannelAppToken string

	// ChannelValues holds field values for the single selected channel.
	ChannelValues map[string]string

	// Channels holds one or more configured channels for onboarding/setup.
	Channels []SetupChannelSelection

	// Address is the listen address (default DefaultGatewayAddress).
	Address string

	// AuthMode controls the generated auth configuration: bearer, apikey, jwt, or none.
	AuthMode string

	// AuthToken is the bearer token value when AuthMode is bearer.
	AuthToken string

	// AuthAPIKey is the API key value when AuthMode is apikey.
	AuthAPIKey string

	// AuthJWTSecret is the signing secret when AuthMode is jwt.
	AuthJWTSecret string
}

type SetupChannelSelection struct {
	ID     string
	Values map[string]string
}

// DefaultModelsForProvider returns the recommended models for a provider.
func DefaultModelsForProvider(provider string) []string {
	if profile, ok := LookupSetupProviderProfile(provider); ok {
		return append([]string(nil), profile.DefaultModels...)
	}
	return nil
}

// DefaultBaseURL returns the default API base URL for a provider.
func DefaultBaseURL(provider string) string {
	if profile, ok := LookupSetupProviderProfile(provider); ok {
		return profile.BaseURL
	}
	return ""
}

// BuildConfig generates a YAML configuration string from the given options.
func BuildConfig(opts SetupOptions) (string, error) {
	if opts.Address == "" {
		opts.Address = DefaultGatewayAddress
	}
	serverAuthToken, authSection, err := renderSetupAuthConfig(opts)
	if err != nil {
		return "", err
	}
	if serverAuthToken != "" {
		serverAuthToken = yamlQuoteString(serverAuthToken)
	}
	channelSection, err := renderSetupChannelsSection(opts)
	if err != nil {
		return "", err
	}

	providerCfg, err := resolveSetupProviderConfig(opts)
	if err != nil {
		return "", err
	}

	data := struct {
		SetupOptions
		AgentDefaultModel string
		ModelsSection     string
		ServerAuth        string
		AuthSection       string
		ChannelSection    string
	}{
		SetupOptions:      opts,
		AgentDefaultModel: providerCfg.AgentDefaultModel,
		ModelsSection:     providerCfg.ModelsSection,
		ServerAuth:        serverAuthToken,
		AuthSection:       authSection,
		ChannelSection:    channelSection,
	}

	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

var configTemplate = template.Must(template.New("config").Parse(`# HopClaw configuration (generated by setup wizard)
server:
  address: "{{.Address}}"
{{- if .ServerAuth}}
  auth_token: {{.ServerAuth}}
{{- end}}
{{- if .AuthSection}}
{{.AuthSection}}
{{- end}}
store:
  backend: memory
agent:
  default_model: "{{.AgentDefaultModel}}"
{{- if .ModelsSection}}
models:
{{.ModelsSection}}
{{- end}}
tools:
  builtins:
    enabled: true
runtime:
  profile: desktop
{{- if .ChannelSection}}
channels:
{{.ChannelSection}}
{{- end}}
`))
