package config

var channelProfiles = []ChannelProfile{
	{
		ID:                  "feishu",
		DisplayName:         "Feishu / Lark",
		Description:         "Feishu or Lark bot with websocket or webhook delivery",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "app_id", ConfigKey: "app_id", Label: "Feishu app ID", Required: true},
			{ID: "app_secret", ConfigKey: "app_secret", Label: "Feishu app secret", Required: true, Secret: true},
		},
	},
	{
		ID:                  "slack",
		DisplayName:         "Slack",
		Description:         "Slack bot token plus app-level Socket Mode token",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "bot_token", ConfigKey: "bot_token", Label: "Slack bot token (xoxb-...)", Required: true, Secret: true},
			{ID: "app_token", ConfigKey: "app_token", Label: "Slack app-level token (xapp-...)", Required: true, Secret: true},
		},
	},
	{
		ID:                  "discord",
		DisplayName:         "Discord",
		Description:         "Discord bot token",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "bot_token", ConfigKey: "bot_token", Label: "Discord bot token", Required: true, Secret: true},
		},
	},
	{
		ID:                  "telegram",
		DisplayName:         "Telegram",
		Description:         "Telegram bot token from @BotFather",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "bot_token", ConfigKey: "bot_token", Label: "Telegram bot token (from @BotFather)", Required: true, Secret: true},
		},
	},
	{
		ID:                  "webhook",
		DisplayName:         "Webhook",
		Description:         "Named outbound webhooks with per-instance callback URLs",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      false,
		OnboardingSupported: false,
	},
	{
		ID:                  "whatsapp",
		DisplayName:         "WhatsApp",
		Description:         "WhatsApp Cloud API integration",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "phone_id", ConfigKey: "phone_id", Label: "WhatsApp Business phone ID", Required: true},
			{ID: "api_token", ConfigKey: "api_token", Label: "WhatsApp API token", Required: true, Secret: true},
			{ID: "base_url", ConfigKey: "base_url", Label: "WhatsApp base URL (optional)"},
		},
	},
	{
		ID:                  "signal",
		DisplayName:         "Signal",
		Description:         "Signal bridge via signal-cli REST API",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "base_url", ConfigKey: "base_url", Label: "Signal base URL", Required: true},
			{ID: "number", ConfigKey: "number", Label: "Signal phone number", Required: true},
			{ID: "auth_token", ConfigKey: "auth_token", Label: "Signal auth token (optional)", Secret: true},
		},
	},
	{
		ID:                  "imessage",
		DisplayName:         "iMessage / BlueBubbles",
		Description:         "BlueBubbles or compatible iMessage bridge",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "base_url", ConfigKey: "base_url", Label: "Bridge base URL", Required: true},
			{ID: "api_key", ConfigKey: "api_key", Label: "Bridge API key", Required: true, Secret: true},
		},
	},
	{
		ID:                  "line",
		DisplayName:         "LINE",
		Description:         "LINE Messaging API channel credentials",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "channel_secret", ConfigKey: "channel_secret", Label: "LINE channel secret", Required: true, Secret: true},
			{ID: "channel_token", ConfigKey: "channel_token", Label: "LINE channel token", Required: true, Secret: true},
		},
	},
	{
		ID:                  "msteams",
		DisplayName:         "Microsoft Teams",
		Description:         "Bot Framework app credentials for Microsoft Teams",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "app_id", ConfigKey: "app_id", Label: "Bot Framework app ID", Required: true},
			{ID: "password", ConfigKey: "password", Label: "Bot Framework app password", Required: true, Secret: true},
		},
	},
	{
		ID:                  "googlechat",
		DisplayName:         "Google Chat",
		Description:         "Google Chat via service account or incoming webhook",
		Implemented:         true,
		SupportLevel:        SupportLevelExperimental,
		SetupSupported:      false,
		OnboardingSupported: false,
	},
	{
		ID:                  "irc",
		DisplayName:         "IRC",
		Description:         "IRC bot with server and nick credentials",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "server", ConfigKey: "server", Label: "IRC server", Required: true},
			{ID: "nick", ConfigKey: "nick", Label: "IRC nick", Required: true},
			{ID: "password", ConfigKey: "password", Label: "IRC password (optional)", Secret: true},
			{ID: "channels", ConfigKey: "channels", Label: "IRC channels (comma-separated)"},
		},
	},
	{
		ID:                  "matrix",
		DisplayName:         "Matrix",
		Description:         "Matrix homeserver, user ID, and access token",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "homeserver", ConfigKey: "homeserver", Label: "Matrix homeserver URL", Required: true},
			{ID: "user_id", ConfigKey: "user_id", Label: "Matrix user ID", Required: true},
			{ID: "access_token", ConfigKey: "access_token", Label: "Matrix access token", Required: true, Secret: true},
		},
	},
	{
		ID:                  "mattermost",
		DisplayName:         "Mattermost",
		Description:         "Mattermost bot token and server URL",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "base_url", ConfigKey: "base_url", Label: "Mattermost base URL", Required: true},
			{ID: "bot_token", ConfigKey: "bot_token", Label: "Mattermost bot token", Required: true, Secret: true},
			{ID: "websocket_url", ConfigKey: "websocket_url", Label: "Mattermost websocket URL (optional)"},
		},
	},
	{
		ID:                  "nextcloud_talk",
		DisplayName:         "Nextcloud Talk",
		Description:         "Nextcloud Talk bridge credentials",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "base_url", ConfigKey: "base_url", Label: "Nextcloud base URL", Required: true},
			{ID: "username", ConfigKey: "username", Label: "Nextcloud username", Required: true},
			{ID: "password", ConfigKey: "password", Label: "Nextcloud app password", Required: true, Secret: true},
		},
	},
	{
		ID:                  "nostr",
		DisplayName:         "Nostr",
		Description:         "Nostr private key plus relay list",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "private_key", ConfigKey: "private_key", Label: "Nostr private key", Required: true, Secret: true},
			{ID: "relays", ConfigKey: "relays", Label: "Nostr relays (comma-separated or one per line)", Required: true, Type: SetupChannelFieldStringList},
		},
	},
	{
		ID:                  "bluebubbles",
		DisplayName:         "BlueBubbles",
		Description:         "BlueBubbles bridge password and base URL",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "base_url", ConfigKey: "base_url", Label: "BlueBubbles base URL", Required: true},
			{ID: "password", ConfigKey: "password", Label: "BlueBubbles password", Required: true, Secret: true},
		},
	},
	{
		ID:                  "synology_chat",
		DisplayName:         "Synology Chat",
		Description:         "Synology Chat via webhook or bot token",
		Implemented:         true,
		SupportLevel:        SupportLevelExperimental,
		SetupSupported:      false,
		OnboardingSupported: false,
	},
	{
		ID:                  "tlon",
		DisplayName:         "Tlon / Urbit",
		Description:         "Urbit Tlon ship URL and code",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "ship_url", ConfigKey: "ship_url", Label: "Ship URL", Required: true},
			{ID: "ship_code", ConfigKey: "ship_code", Label: "Ship code", Required: true, Secret: true},
		},
	},
	{
		ID:                  "twitch",
		DisplayName:         "Twitch",
		Description:         "Twitch IRC-style bot credentials",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "oauth_token", ConfigKey: "oauth_token", Label: "Twitch OAuth token", Required: true, Secret: true},
			{ID: "nick", ConfigKey: "nick", Label: "Twitch bot nick", Required: true},
			{ID: "channels", ConfigKey: "channels", Label: "Twitch channels (comma-separated)"},
		},
	},
	{
		ID:                  "zalo",
		DisplayName:         "Zalo",
		Description:         "Official Zalo app credentials",
		Implemented:         true,
		SupportLevel:        SupportLevelExperimental,
		SetupSupported:      false,
		OnboardingSupported: false,
	},
	{
		ID:                  "zalouser",
		DisplayName:         "Zalo User",
		Description:         "Zalo user bridge via cookie and device identifiers",
		Implemented:         true,
		SupportLevel:        SupportLevelSupported,
		SetupSupported:      true,
		OnboardingSupported: true,
		Fields: []SetupChannelField{
			{ID: "cookie", ConfigKey: "cookie", Label: "Zalo session cookie", Required: true, Secret: true},
			{ID: "imei", ConfigKey: "imei", Label: "Device IMEI (optional)", Secret: true},
			{ID: "base_url", ConfigKey: "base_url", Label: "Base URL (optional)"},
		},
	},
}
