package toolruntime

import "github.com/fulcrus/hopclaw/skill"

func coreToolDefs(cfg BuiltinsConfig) []builtinToolDef {
	return wrapBuiltinManifests([]skill.ToolManifest{
		{
			Name:            "fs.list",
			Description:     "List files and directories within the workspace root.",
			InputSchema:     builtinFSListSchema(),
			OutputSchema:    builtinFSListOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.tree",
			Description:     "Render a bounded directory tree within the workspace root.",
			InputSchema:     builtinFSTreeSchema(),
			OutputSchema:    builtinFSTreeOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.find",
			Description:     "Find files or directories within the workspace root.",
			InputSchema:     builtinFSFindSchema(),
			OutputSchema:    builtinFSFindOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.grep",
			Description:     "Search file contents within the workspace root.",
			InputSchema:     builtinFSGrepSchema(),
			OutputSchema:    builtinFSGrepOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.read",
			Description:     "Read a file from the workspace root with optional offset and limit.",
			InputSchema:     builtinFSReadSchema(),
			OutputSchema:    builtinFSReadOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.stat",
			Description:     "Read filesystem metadata for a path within the workspace root.",
			InputSchema:     builtinFSStatSchema(),
			OutputSchema:    builtinFSStatOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:            "fs.hash",
			Description:     "Compute a content hash for a file within the workspace root.",
			InputSchema:     builtinFSHashSchema(),
			OutputSchema:    builtinFSHashOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:             "fs.write",
			Description:      "Create, overwrite, or append a file within the workspace root.",
			InputSchema:      builtinFSWriteSchema(),
			OutputSchema:     builtinFSWriteOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			ExecutionKey:     "fs:{path}",
			RequiresApproval: true,
		},
		{
			Name:             "fs.edit",
			Description:      "Replace text in a file within the workspace root.",
			InputSchema:      builtinFSEditSchema(),
			OutputSchema:     builtinFSEditOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			ExecutionKey:     "fs:{path}",
			RequiresApproval: true,
		},
		{
			Name:             "fs.patch",
			Description:      "Apply a unified diff patch within the workspace root.",
			InputSchema:      builtinFSPatchSchema(),
			OutputSchema:     builtinFSPatchOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			ExecutionKey:     "fs:{path}",
			RequiresApproval: true,
			Timeout:          cfg.DefaultExecTimeout,
		},
		{
			Name:            "fs.diff",
			Description:     "Generate a unified diff between two files within the workspace root.",
			InputSchema:     builtinFSDiffSchema(),
			OutputSchema:    builtinFSDiffOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:diff",
		},
		{
			Name:            "fs.changes",
			Description:     "List all files modified in this session, optionally showing diffs.",
			InputSchema:     builtinFSChangesSchema(),
			OutputSchema:    builtinFSChangesOutputSchema(),
			SideEffectClass: "read",
			Idempotent:      true,
			ExecutionKey:    "fs:changes",
		},
		{
			Name:             "fs.revert",
			Description:      "Revert a file to its state before session modifications.",
			InputSchema:      builtinFSRevertSchema(),
			OutputSchema:     builtinFSRevertOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			RequiresApproval: true,
			ExecutionKey:     "fs:{path}",
		},
		{
			Name:             "fs.delete",
			Description:      "Delete a file or empty directory within the workspace root.",
			InputSchema:      builtinFSDeleteSchema(),
			OutputSchema:     builtinFSDeleteOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			RequiresApproval: true,
			ExecutionKey:     "fs:{path}",
		},
		{
			Name:             "fs.move",
			Description:      "Move or rename a file or directory within the workspace root.",
			InputSchema:      builtinFSMoveSchema(),
			OutputSchema:     builtinFSMoveOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			RequiresApproval: true,
			ExecutionKey:     "fs:{source}",
		},
		{
			Name:            "fs.copy",
			Description:     "Copy a file within the workspace root.",
			InputSchema:     builtinFSCopySchema(),
			OutputSchema:    builtinFSCopyOutputSchema(),
			SideEffectClass: "local_write",
			Idempotent:      true,
			ExecutionKey:    "fs:{source}",
		},
		{
			Name:            "fs.mkdir",
			Description:     "Create a directory (and parents) within the workspace root.",
			InputSchema:     builtinFSMkdirSchema(),
			OutputSchema:    builtinFSMkdirOutputSchema(),
			SideEffectClass: "local_write",
			Idempotent:      true,
			ExecutionKey:    "fs:{path}",
		},
		{
			Name:             "fs.append",
			Description:      "Append content to the end of a file within the workspace root.",
			InputSchema:      builtinFSAppendSchema(),
			OutputSchema:     builtinFSAppendOutputSchema(),
			SideEffectClass:  "local_write",
			Idempotent:       false,
			RequiresApproval: true,
			ExecutionKey:     "fs:{path}",
		},
	})
}
